#pragma once

// A bounded SPSC transport receipt.  It establishes only declared route and
// raw-word integrity inside this process; it does not authenticate a physical
// source, prove body reafference, or bind a resident update.

#include <cstddef>
#include <cstdint>
#include <optional>
#include <span>
#include <utility>
#include <vector>

#include "hardware_native/bcc32_persistent_kernel.hpp"

namespace substrate::bcc32::device_body_return_route {

using ActionReturnTicket = persistent_kernel::ActionReturnTicket;
using BoundaryWord = persistent_kernel::BoundaryWord;

struct RouteIdentity {
  std::uint64_t producer_instance = 0u;
  std::uint64_t source_epoch = 0u;

  friend bool operator==(const RouteIdentity&, const RouteIdentity&) = default;
};

enum class RouteStatus : std::uint8_t {
  idle,
  published,
  consumed,
  rejected,
};

enum class RouteRejection : std::uint8_t {
  none,
  zero_route_identity,
  zero_ticket,
  occupied,
  route_identity_mismatch,
  ticket_mismatch,
  sequence_mismatch,
  raw_word_mutation,
  replay,
};

// Passive observation only.  The digest is generated by this route and is not
// accepted as an authority from a publisher or consumer.
struct DeviceBodyReturnReceipt {
  RouteIdentity route{};
  ActionReturnTicket ticket{};
  std::uint64_t route_sequence = 0u;
  std::uint64_t raw_digest = 0u;
  std::size_t raw_word_count = 0u;
  RouteStatus status = RouteStatus::idle;
  RouteRejection rejection = RouteRejection::none;
  bool pending = false;
};

struct ConsumedDeviceBodyReturn {
  DeviceBodyReturnReceipt receipt{};
  std::vector<BoundaryWord> raw_words{};
};

class DeviceBodyReturnRoute final {
 public:
  explicit DeviceBodyReturnRoute(RouteIdentity route) noexcept : route_(route) {
    if (!route_valid(route_))
      rejection_ = RouteRejection::zero_route_identity;
  }

  DeviceBodyReturnRoute(const DeviceBodyReturnRoute&) = delete;
  DeviceBodyReturnRoute& operator=(const DeviceBodyReturnRoute&) = delete;
  DeviceBodyReturnRoute(DeviceBodyReturnRoute&&) = delete;
  DeviceBodyReturnRoute& operator=(DeviceBodyReturnRoute&&) = delete;

  [[nodiscard]] RouteIdentity route_identity() const noexcept { return route_; }

  // Copies raw words before publication.  A caller cannot alter the pending
  // route by later mutating its own buffer.
  [[nodiscard]] bool publish(const ActionReturnTicket& ticket,
                             std::span<const BoundaryWord> raw_words) {
    if (!route_valid(route_))
      return reject(RouteRejection::zero_route_identity);
    if (!ticket_valid(ticket))
      return reject(RouteRejection::zero_ticket);
    if (pending_)
      return reject(RouteRejection::occupied);
    if (next_sequence_ == 0u)
      return reject(RouteRejection::sequence_mismatch);

    pending_ticket_ = ticket;
    pending_sequence_ = next_sequence_;
    pending_words_.assign(raw_words.begin(), raw_words.end());
    pending_digest_ = digest(route_, pending_ticket_, pending_sequence_, pending_words_);
    pending_ = true;
    ++next_sequence_;
    status_ = RouteStatus::published;
    rejection_ = RouteRejection::none;
    return true;
  }

  // The claimant supplies route/ticket/sequence and raw words, never a digest.
  // The route recomputes the digest and admits exactly one matching consume.
  [[nodiscard]] std::optional<ConsumedDeviceBodyReturn> consume(
      RouteIdentity claimed_route, const ActionReturnTicket& ticket,
      std::uint64_t route_sequence, std::span<const BoundaryWord> raw_words) {
    if (!pending_)
      return reject_consume(RouteRejection::replay);
    if (claimed_route != route_)
      return reject_consume(RouteRejection::route_identity_mismatch);
    if (!ticket_valid(ticket))
      return reject_consume(RouteRejection::zero_ticket);
    if (ticket != pending_ticket_)
      return reject_consume(RouteRejection::ticket_mismatch);
    if (route_sequence == 0u || route_sequence != pending_sequence_)
      return reject_consume(RouteRejection::sequence_mismatch);
    if (digest(route_, ticket, route_sequence, raw_words) != pending_digest_)
      return reject_consume(RouteRejection::raw_word_mutation);

    ConsumedDeviceBodyReturn consumed{receipt(), std::move(pending_words_)};
    pending_ = false;
    pending_ticket_ = {};
    pending_sequence_ = 0u;
    pending_digest_ = 0u;
    status_ = RouteStatus::consumed;
    rejection_ = RouteRejection::none;
    consumed.receipt.status = RouteStatus::consumed;
    consumed.receipt.rejection = RouteRejection::none;
    consumed.receipt.pending = false;
    last_consumed_receipt_ = consumed.receipt;
    return consumed;
  }

  // Polling is passive: it neither publishes nor consumes and cannot advance
  // the route sequence.
  [[nodiscard]] DeviceBodyReturnReceipt receipt() const noexcept {
    if (pending_)
      return {route_, pending_ticket_, pending_sequence_, pending_digest_,
              pending_words_.size(), status_, rejection_, true};
    if (last_consumed_receipt_.route_sequence != 0u) {
      DeviceBodyReturnReceipt durable = last_consumed_receipt_;
      durable.status = status_;
      durable.rejection = rejection_;
      durable.pending = false;
      return durable;
    }
    return {route_, {}, 0u, 0u, 0u, status_, rejection_, false};
  }

 private:
  static constexpr bool route_valid(RouteIdentity route) noexcept {
    return route.producer_instance != 0u && route.source_epoch != 0u;
  }

  static constexpr bool ticket_valid(const ActionReturnTicket& ticket) noexcept {
    return ticket.issuer_instance != 0u && ticket.action_sequence != 0u && ticket.nonce != 0u;
  }

  static constexpr std::uint64_t mix(std::uint64_t state, std::uint64_t word) noexcept {
    state ^= word;
    state *= 1099511628211ull;
    return state;
  }

  static std::uint64_t digest(RouteIdentity route, const ActionReturnTicket& ticket,
                              std::uint64_t sequence,
                              std::span<const BoundaryWord> raw_words) noexcept {
    std::uint64_t state = 1469598103934665603ull;
    state = mix(state, route.producer_instance);
    state = mix(state, route.source_epoch);
    state = mix(state, ticket.issuer_instance);
    state = mix(state, ticket.action_sequence);
    state = mix(state, ticket.nonce);
    state = mix(state, sequence);
    state = mix(state, static_cast<std::uint64_t>(raw_words.size()));
    for (const BoundaryWord word : raw_words)
      state = mix(state, word);
    return state == 0u ? 1u : state;
  }

  [[nodiscard]] bool reject(RouteRejection rejection) noexcept {
    status_ = RouteStatus::rejected;
    rejection_ = rejection;
    return false;
  }

  [[nodiscard]] std::optional<ConsumedDeviceBodyReturn> reject_consume(
      RouteRejection rejection) noexcept {
    status_ = RouteStatus::rejected;
    rejection_ = rejection;
    return std::nullopt;
  }

  const RouteIdentity route_;
  std::uint64_t next_sequence_ = 1u;
  ActionReturnTicket pending_ticket_{};
  std::uint64_t pending_sequence_ = 0u;
  std::uint64_t pending_digest_ = 0u;
  std::vector<BoundaryWord> pending_words_{};
  DeviceBodyReturnReceipt last_consumed_receipt_{};
  RouteStatus status_ = RouteStatus::idle;
  RouteRejection rejection_ = RouteRejection::none;
  bool pending_ = false;
};

}  // namespace substrate::bcc32::device_body_return_route
