#ifndef HARDWARE_NATIVE_DIRECT_ADULT_PERSISTENT_CUH
#define HARDWARE_NATIVE_DIRECT_ADULT_PERSISTENT_CUH

#include "direct_adult_core.cuh"

namespace substrate::direct_adult_core {
bool query_cooperative_adult_launch_dims(int& out_grid_blocks, int& out_block_dim);
__global__ void persistent_direct_adult_kernel(
    DirectNode* nodes,
    DirectRoute* routes,
    std::uint32_t node_count,
    std::uint32_t route_capacity,
    const DirectBoundaryPort* boundary_ports,
    std::uint32_t boundary_port_count,
    ActivityEvent* ingress_queue,
    ResidentContactEpochReceipt* ingress_contact_credentials,
    ResidentActualFrontier* actual_frontier,
    ResidentActivationSoaPlane* activation_plane,
    ResidentMultiHorizonPredictionFrontier* causal_credit_predictions,
    ResidentMismatchOmissionRuntime* mismatch_omission,
    IngressRingControl* ingress_control,
    ConsequenceIngressEvent* consequence_queue,
    IngressRingControl* consequence_control,
    MotorEvent* egress_queue,
    std::uint32_t* egress_head,
    std::uint32_t* egress_tail,
    EligibilityRecord* eligibility_table,
    std::uint32_t* live_eligibility_count,
    std::uint64_t* eligibility_claim_directory,
    std::uint32_t* eligibility_claim_locks,
    std::uint32_t* eligibility_record_generations,
    AsynchronousTicket* ticket_table,
    std::uint32_t* ticket_count,
    std::uint32_t* ticket_table_locks,
    std::uint32_t* claim_incarnation_counter,
    DirectActionOccurrence* action_occurrences,
    DirectActionParticipationLink* action_participation_links,
    std::uint32_t action_participant_capacity,
    ResidentPublicMotorTrajectory* resident_motor_trajectory,
    direct_network::DirectResidentLanguageRuntimeBlock* resident_language,
    DirectAdultActionControlRuntimeBlock* action_control_runtime,
    direct_network::DirectAffectBodyState* affect_body_state,
    direct_network::ResidentWantingLikingProfileV1* wanting_liking_state,
    ResolvedConsequenceContext* resolved_consequence_ctx,
    AttractorBasinState* attractor_state,
    ResidentCueSalienceTable* cue_salience_table,
    std::int32_t* node_incoming_excitation,
    std::int32_t* node_slow_context_q16,
    DelayedSparsePacket* delayed_packets,
    std::uint32_t* delayed_packet_live_count,
    std::uint32_t* delayed_packet_free_head,
    std::uint32_t* delayed_packet_next_free,
    DelayedPacketIdentity* delayed_packet_identities,
    RouteTransportPhaseView route_transport,
    std::uint64_t* route_opportunity_incarnations,
    std::uint32_t* route_causal_pin_bits,
    NodeCausalParticipation* node_active_participation,
    NodeCausalParticipation* node_next_participation,
    std::uint32_t* node_active_participation_locks,
    std::uint32_t* node_next_participation_locks,
    std::uint32_t* node_active_ancestry_incomplete,
    std::uint32_t* node_next_ancestry_incomplete,
    DirectParticipationDescriptor* participation_staging,
    std::uint32_t* participation_staging_count, std::uint32_t participation_staging_capacity,
    AdultCoreMetrics* device_metrics,
    AdultExecutionConfig config,
    volatile std::uint32_t* stop_flag,
    volatile std::uint32_t* resident_tick,
    volatile std::uint32_t* epoch_limit,
    ResidentAdultEpochSnapshot* device_epoch_snapshot,
    ResidentDevelopmentWorkspace resident_development,
    DirectBrain brain,
    DirectEfferenceCopy* efference_ring,
    std::uint32_t* efference_head,
    std::uint32_t* efference_tail,
    AdultCoreObserverSnapshot* observer_snapshot);
}  // namespace substrate::direct_adult_core

#endif  // HARDWARE_NATIVE_DIRECT_ADULT_PERSISTENT_CUH
