#include <cuda_runtime.h>
#include <cstdio>
#include "hardware_native/direct_causal_program.cuh"
using namespace substrate::direct_causal_program;
struct Receipt { unsigned green,initial_short,learned_deep,urgent_short,support_deep,capacity_green; std::uint64_t victim; };
__device__ Program make_program(unsigned long long id,unsigned depth,unsigned steps){Program p{};p.identity=id;p.depth=depth;p.step_count=steps;p.initiation_participation_identity=id+0x1000;p.initiation_parent_eligibility_ref=(5ull<<32)|4ull;p.initiation_expiry_tick=999;return p;}
__global__ void run(Receipt* r){if(blockIdx.x||threadIdx.x)return;constexpr unsigned ctx=0xCA61;PredictiveProfile s{},d{};s.structure_identity=11;d.structure_identity=22;for(int i=0;i<6;++i){observe_use(&s,2,kQ16One/12);observe_return(&s,ctx,kQ16One/2,kQ16One/16,true);observe_control(&s,true,true);}for(int i=0;i<4;++i){observe_use(&d,7,3*kQ16One/4);observe_return(&d,ctx,kQ16One,kQ16One/8,true);observe_control(&d,false,false);}CurrentState relaxed{};r->initial_short=prospective_score(s,ctx,relaxed)>prospective_score(d,ctx,relaxed);for(int i=0;i<16;++i)observe_control(&d,true,true);r->learned_deep=prospective_score(d,ctx,relaxed)>prospective_score(s,ctx,relaxed);CurrentState urgent{};urgent.urgency_q16=kQ16One;urgent.resource_pressure_q16=kQ16One;r->urgent_short=prospective_score(s,ctx,urgent)>prospective_score(d,ctx,urgent);CurrentState support{};support.resource_pressure_q16=kQ16One;support.social_relief_q16=3*kQ16One/4;support.social_relief_authenticated=1;r->support_deep=prospective_score(d,ctx,support)>prospective_score(s,ctx,support);
ProgramBank b{};std::uint64_t ev=0;auto* old=admit_program(&b,make_program(0x79,1,5),&ev);for(int i=0;i<3;++i){observe_use(&old->profile,7,kQ16One/2);observe_return(&old->profile,1,kQ16One,0,true);observe_control(&old->profile,true,true);}auto* avoid=admit_program(&b,make_program(0xBAD,0,2),&ev);for(int i=0;i<2;++i){observe_use(&avoid->profile,2,kQ16One/8);observe_return(&avoid->profile,2,-kQ16One,0,true);observe_control(&avoid->profile,true,true);}for(unsigned i=0;i<14;++i){auto* f=admit_program(&b,make_program(0x1000+i,0,1),&ev);observe_use(&f->profile,1,kQ16One/32);}auto* newer=admit_program(&b,make_program(0x118,2,7),&ev);for(int i=0;i<2;++i){observe_use(&newer->profile,10,3*kQ16One/4);observe_return(&newer->profile,1,3*kQ16One/2,0,true);observe_control(&newer->profile,true,true);}r->victim=ev;r->capacity_green=b.count==16&&b.evictions==1&&find_program(&b,0x79)&&find_program(&b,0xBAD)&&find_program(&b,0x118)&&ev>=0x1000&&ev<0x100e;r->green=r->initial_short&&r->learned_deep&&r->urgent_short&&r->support_deep&&r->capacity_green;}
int main(){Receipt *d=nullptr,h{};if(cudaMalloc(&d,sizeof(Receipt))!=cudaSuccess)return 2;cudaMemset(d,0,sizeof(Receipt));run<<<1,1>>>(d);if(cudaDeviceSynchronize()!=cudaSuccess)return 3;cudaMemcpy(&h,d,sizeof(h),cudaMemcpyDeviceToHost);cudaFree(d);std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_CUDA_%s initial_bytes=38 learned_bytes=79 learned_depth=1 learned_steps=5 urgent_bytes=38 supported_bytes=79 capacity=16 new_bytes=118 new_depth=2 victim=%llu\n",h.green?"GREEN":"RED",static_cast<unsigned long long>(h.victim));return h.green?0:1;}
