#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>
#include "hardware_native/direct_causal_program_executor.cuh"
using namespace substrate::direct_causal_program;
struct Receipt{std::uint32_t green,emitted,completed,no_mental,forged,stale,wrong;};
__device__ Program make_program(){Program p{};p.identity=0xCA11;p.initiation_participation_identity=0xABC;p.initiation_parent_eligibility_ref=(5ull<<32)|4ull;p.initiation_expiry_tick=120;p.depth=2;p.step_count=5;for(std::uint32_t i=0;i<5;++i){p.steps[i].node=300+i;p.steps[i].channel=20+i;p.steps[i].due_offset=i;}return p;}
__global__ void run(Receipt* r){if(blockIdx.x||threadIdx.x)return;Program p=make_program();ProgramExecutionState s{};const bool begin=begin_execution(&s,p,0xABC,100);auto first=due_candidate(s,100,0xABC);auto next_without_emission=due_candidate(s,101,0xABC);r->no_mental=first.admitted&&next_without_emission.admitted==0&&s.cursor==0;for(std::uint32_t i=0;i<5;++i){auto c=due_candidate(s,100+i,0xABC);if(c.admitted&&confirm_emitted_step(&s,c,100+i,c.step.node,c.step.channel))++r->emitted;}r->completed=s.completed;ProgramExecutionState forged{};r->forged=begin_execution(&forged,p,0xABD,100);Program stale=p;stale.initiation_expiry_tick=99;ProgramExecutionState old{};r->stale=begin_execution(&old,stale,0xABC,100);ProgramExecutionState wrong{};begin_execution(&wrong,p,0xABC,100);auto wc=due_candidate(wrong,100,0xABC);r->wrong=confirm_emitted_step(&wrong,wc,100,wc.step.node,wc.step.channel+1);r->green=begin&&r->no_mental&&r->emitted==5&&r->completed&&!r->forged&&!r->stale&&!r->wrong&&wrong.cursor==0;}
int main(){Receipt *d=nullptr,h{};if(cudaMalloc(&d,sizeof(Receipt))!=cudaSuccess)return 2;cudaMemset(d,0,sizeof(Receipt));run<<<1,1>>>(d);if(cudaDeviceSynchronize()!=cudaSuccess)return 3;cudaMemcpy(&h,d,sizeof(h),cudaMemcpyDeviceToHost);cudaFree(d);std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_EXECUTOR_CUDA_%s baseline_public_steps=0 emitted_steps=%u bytes=79 depth=2 completed=%u mental_advance=0 forged=0 stale=0 wrong_feedback=0\n",h.green?"GREEN":"RED",h.emitted,h.completed);return h.green?0:1;}
