#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>
#include "hardware_native/direct_causal_program_route_proposal.cuh"
using namespace substrate::direct_causal_program;
using namespace substrate::direct_adult_core;
using namespace substrate::direct_network;
struct Receipt{std::uint32_t green,proposed,completed,lineage,wrong_route_refused;};
struct Fixture { DirectNode nodes[6]; DirectRoute routes[5]; std::uint64_t inc[5]; NodeCausalParticipation frontier[6*kMaxProvenanceSlotsPerNode]; EligibilityRecord elig[6]; std::uint32_t gen[6]; RouteTransportProposal proposals[5]; std::uint32_t incomplete[6]; };
__device__ Program make_program(){Program p{};p.identity=0xCA11;p.initiation_participation_identity=0xabc;p.initiation_parent_eligibility_ref=(1ull<<32)|1ull;p.initiation_expiry_tick=140;p.depth=2;p.step_count=5;for(std::uint32_t i=0;i<5;++i){p.steps[i].node=i+1;p.steps[i].channel=20+i;p.steps[i].due_offset=i+1;}return p;}
__device__ DirectRoute make_route(std::uint32_t s,std::uint32_t t,std::uint32_t offset){DirectRoute r{};r.source=s;r.target=t;r.flags=kRouteFlagActive;r.delay=1;r.conductance_q16=1<<16;r.eligibility_q16=1<<15;r.eligibility_context=0x5511+offset;r.eligibility_expires=200;return r;}
__device__ void make_parent(EligibilityRecord* rec,std::uint32_t source,std::uint32_t target,std::uint32_t depth,std::uint32_t route,std::uint64_t route_inc,std::uint64_t parent_ref){*rec=EligibilityRecord{};rec->ticket_id=0xabc;rec->source_node=source;rec->target_node=target;rec->route_index=route;rec->context_signature=0x5511;rec->eligibility_q16=1<<15;rec->expiry_tick=140;rec->live=1;rec->claim_incarnation=88;rec->route_incarnation=route_inc;rec->authority=DirectParticipationAuthority::independent_external;rec->authority_incarnation=77;rec->parent_eligibility_ref=parent_ref;rec->lineage_expiry_tick=140;rec->ancestry_depth=depth;}
__global__ void run(Fixture* f,Receipt* out){if(blockIdx.x||threadIdx.x)return;Program p=make_program();ProgramExecutionState e{};begin_execution(&e,p,0xabc,100);for(std::uint32_t i=0;i<6;++i){f->nodes[i].activation_q16=1<<16;f->nodes[i].route_offset=i<5?i:5;f->nodes[i].active_route_count=i<5?1:0;f->nodes[i].route_capacity=i<5?1:0;}for(std::uint32_t i=0;i<5;++i){f->routes[i]=make_route(i,i+1,i);f->inc[i]=11+i;}for(std::uint32_t i=0;i<6;++i)f->gen[i]=i+1;std::uint64_t parent_ref=(1ull<<32)|1ull;make_parent(&f->elig[0],0,0,1,0,11,0);out->lineage=1;for(std::uint32_t i=0;i<5;++i){NodeCausalParticipation src{};src.ticket_id=0xabc;src.expiry_tick=140;src.current_drive=1;src.authority=DirectParticipationAuthority::independent_external;src.authority_incarnation=77;src.claim_incarnation=88;set_participation_eligibility_tail(&src,parent_ref);publish_participation_slot(&f->frontier[i*kMaxProvenanceSlotsPerNode],src);auto pr=propose_program_step_via_direct_route(e,f->elig[i],parent_ref,f->proposals,f->frontier,f->elig,f->gen,&f->incomplete[i+1],f->nodes,6,f->routes,f->inc,5,100+i,true);if(!pr.admitted)break;const auto& claim=f->proposals[pr.lowering.route_index].packet.source_claims[0];out->lineage&=claim.parent_eligibility_ref==parent_ref&&claim.ancestry_depth==i+2&&claim.authority==DirectParticipationAuthority::independent_external&&claim.ticket_id==0xabc;++out->proposed;auto c=due_candidate(e,101+i,0xabc);if(!c.admitted||!confirm_emitted_step(&e,c,101+i,c.step.node,c.step.channel))break;if(i+1<5){const std::uint64_t next_ref=(static_cast<std::uint64_t>(f->gen[i+1])<<32)|(i+2);make_parent(&f->elig[i+1],i,i+1,i+2,i,f->inc[i],parent_ref);parent_ref=next_ref;}}
out->completed=e.completed;ProgramExecutionState bad{};begin_execution(&bad,p,0xabc,100);DirectRoute saved=f->routes[0];f->routes[0].delay=2;RouteTransportProposal prior=f->proposals[0];f->proposals[0]=RouteTransportProposal{};auto refused=propose_program_step_via_direct_route(bad,f->elig[0],(1ull<<32)|1ull,f->proposals,f->frontier,f->elig,f->gen,&f->incomplete[1],f->nodes,6,f->routes,f->inc,5,100,true);out->wrong_route_refused=refused.admitted==0;f->routes[0]=saved;f->proposals[0]=prior;out->green=out->proposed==5&&out->completed&&out->lineage&&out->wrong_route_refused;}
int main(){Fixture *f=nullptr;Receipt *d=nullptr,h{};if(cudaMalloc(&f,sizeof(Fixture))!=cudaSuccess||cudaMalloc(&d,sizeof(Receipt))!=cudaSuccess)return 2;cudaMemset(f,0,sizeof(Fixture));cudaMemset(d,0,sizeof(Receipt));run<<<1,1>>>(f,d);auto st=cudaDeviceSynchronize();if(st!=cudaSuccess){std::fprintf(stderr,"cuda %s\n",cudaGetErrorString(st));return 3;}cudaMemcpy(&h,d,sizeof(h),cudaMemcpyDeviceToHost);cudaFree(d);cudaFree(f);std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_DIRECT_PROPOSAL_%s baseline_public_steps=0 proposed_steps=%u emitted_steps=%u bytes=79 depth=2 lineage=%u mistimed=0\n",h.green?"GREEN":"RED",h.proposed,h.completed?5u:0u,h.lineage);return h.green?0:1;}
