#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <cstdint>
#include <cstdio>
#include <vector>
#include "hardware_native/direct_causal_program_route_proposal.cuh"
namespace cg=cooperative_groups;
using namespace substrate::direct_causal_program;
using namespace substrate::direct_adult_core;
using namespace substrate::direct_network;
constexpr std::uint32_t N=6,R=5,CAP=kMaxDelayedSparsePackets*kRouteTransportProducerWidth;
struct P {DirectNode* nodes;DirectRoute* routes;std::uint64_t* inc;std::int32_t* incoming;DelayedSparsePacket* packets;std::uint32_t* packet_live,*free_head,*next_free;DelayedPacketIdentity* identities;NodeCausalParticipation* active,*next;std::uint32_t* active_inc,*next_inc;DirectParticipationDescriptor* staging;std::uint32_t* staging_count;EligibilityRecord* elig;std::uint32_t* live_elig;std::uint64_t* directory;std::uint32_t* generations;RouteTransportProposal* proposals;EligibilityBatchClaim* claims;std::uint32_t* scan_a,*scan_b,*free_slots,*owners,*node_owners,*cursor;AdultCoreMetrics* metrics;};
struct State {ProgramExecutionState exec;std::uint64_t parent_ref;std::uint32_t parent_slot;std::uint32_t steps;std::uint32_t lineage;std::uint32_t failed;};
__device__ Program program(){Program p{};p.identity=0xCA11;p.initiation_participation_identity=0xabc;p.initiation_parent_eligibility_ref=(1ull<<32)|1ull;p.initiation_expiry_tick=150;p.depth=2;p.step_count=5;for(std::uint32_t i=0;i<5;++i){p.steps[i].node=i+1;p.steps[i].channel=20+i;p.steps[i].due_offset=i+1;}return p;}
__global__ void init_state(State* s){if(blockIdx.x||threadIdx.x)return;s->parent_ref=(1ull<<32)|1ull;s->parent_slot=0;s->lineage=1;auto p=program();if(!begin_execution(&s->exec,p,0xabc,100))s->failed=1;}
__global__ void prepare_frontier(P q,std::uint32_t tick){std::uint32_t i=blockIdx.x*blockDim.x+threadIdx.x;std::uint32_t slots=N*kMaxProvenanceSlotsPerNode;if(i<slots){auto v=read_participation_slot(q.active+i);if(v.ticket_id==0||v.expiry_tick<tick)v=NodeCausalParticipation{};v.current_drive=0;publish_participation_slot(q.next+i,v);}if(i<N)q.next_inc[i]=0;}
__global__ void propose_step(P q,State* s,std::uint32_t tick){if(blockIdx.x||threadIdx.x||s->failed)return;auto pr=propose_program_step_via_direct_route(s->exec,q.elig[s->parent_slot],s->parent_ref,q.proposals,q.active,q.elig,q.generations,q.next_inc+s->exec.active_program.steps[s->exec.cursor].node,q.nodes,N,q.routes,q.inc,R,tick,true);if(!pr.admitted)s->failed=1;}
__global__ void materialize(P q,std::uint32_t tick){auto g=cg::this_thread_block();materialize_route_transport_proposals(g,q.proposals,R,tick,N,q.cursor,q.packets,q.packet_live,q.free_head,q.next_free,q.identities,q.scan_a,q.scan_b,kMaxDelayedSparsePackets,q.free_slots,q.owners,q.next_inc,q.metrics);}
// Deliver only due packets + child eligibility admission. Avoid the function's immediate-proposal tail so this assay isolates the Program proposal.
__global__ void deliver_due(P q,std::uint32_t tick){auto g=cg::this_thread_block();std::uint32_t tid=g.thread_rank();std::uint32_t stride=g.size();std::uint32_t live=*q.packet_live;for(std::uint32_t i=tid;i<CAP;i+=stride)q.claims[i]=EligibilityBatchClaim{};g.sync();for(std::uint32_t rank=tid;rank<live;rank+=stride){std::uint32_t packet=q.next_free[rank];if(packet<kMaxDelayedSparsePackets&&q.packets[packet].live==static_cast<std::uint32_t>(DelayedPacketSlotState::published)&&q.packets[packet].due_tick<=tick)prepare_delayed_sparse_packet_batch(q.packets,q.identities,q.nodes,q.routes,q.inc,nullptr,N,R,q.incoming,q.elig,q.generations,q.claims,CAP,q.next_inc,packet,rank,tick,substrate::direct_adult_core::kQ16One,64u,q.metrics);}g.sync();deterministic_eligibility_batch(g,q.claims,live*kRouteTransportProducerWidth,q.elig,q.live_elig,q.directory,q.generations,q.owners,q.scan_a,q.scan_b,q.free_slots,q.next,q.next_inc,q.node_owners,N,q.staging,q.staging_count,32u,tick,q.metrics);}
__global__ void observe_and_confirm(P q,State* s,std::uint32_t due_tick){if(blockIdx.x||threadIdx.x||s->failed)return;std::uint32_t target=s->exec.active_program.steps[s->exec.cursor].node;std::uint64_t child=0;std::uint32_t slot=substrate::direct_adult_core::kInvalidIndex;for(std::uint32_t i=0;i<kMaxLiveEligibilityRecords;++i){auto r=q.elig[i];if(r.live&&r.parent_eligibility_ref==s->parent_ref&&r.target_node==target&&r.ticket_id==0xabc){child=eligibility_record_ref(i,q.generations[i]);slot=i;s->lineage&=r.ancestry_depth==s->steps+2&&r.authority==DirectParticipationAuthority::independent_external&&r.route_index==s->steps;break;}}if(child==0||slot==substrate::direct_adult_core::kInvalidIndex){s->failed=1;return;}bool part=false;for(std::uint32_t j=0;j<kMaxProvenanceSlotsPerNode;++j){auto p=read_participation_slot(q.next+target*kMaxProvenanceSlotsPerNode+j);if(p.ticket_id==0xabc&&p.current_drive&&participation_eligibility_tail(p)==child){part=true;break;}}if(!part){s->failed=1;return;}auto c=due_candidate(s->exec,due_tick,0xabc);if(!c.admitted||!confirm_emitted_step(&s->exec,c,due_tick,c.step.node,c.step.channel)){s->failed=1;return;}s->parent_ref=child;s->parent_slot=slot;++s->steps;}
__global__ void commit_frontier(P q){std::uint32_t i=blockIdx.x*blockDim.x+threadIdx.x;std::uint32_t slots=N*kMaxProvenanceSlotsPerNode;if(i<slots){publish_participation_slot(q.active+i,read_participation_slot(q.next+i));publish_participation_slot(q.next+i,NodeCausalParticipation{});}if(i<N){q.active_inc[i]=q.next_inc[i];q.next_inc[i]=0;}}
static void ck(cudaError_t s,const char* w){if(s!=cudaSuccess){std::fprintf(stderr,"%s: %s\n",w,cudaGetErrorString(s));std::exit(2);}}
template<class T>T* al(std::size_t n=1){T*p=nullptr;ck(cudaMalloc(&p,sizeof(T)*n),"alloc");ck(cudaMemset(p,0,sizeof(T)*n),"zero");return p;}
int main(){P q{};q.nodes=al<DirectNode>(N);q.routes=al<DirectRoute>(R);q.inc=al<std::uint64_t>(R);q.incoming=al<std::int32_t>(N);q.packets=al<DelayedSparsePacket>(kMaxDelayedSparsePackets);q.packet_live=al<std::uint32_t>();q.free_head=al<std::uint32_t>();q.next_free=al<std::uint32_t>(kMaxDelayedSparsePackets);q.identities=al<DelayedPacketIdentity>(kDelayedPacketIdentityCapacity);q.active=al<NodeCausalParticipation>(N*kMaxProvenanceSlotsPerNode);q.next=al<NodeCausalParticipation>(N*kMaxProvenanceSlotsPerNode);q.active_inc=al<std::uint32_t>(N);q.next_inc=al<std::uint32_t>(N);q.staging=al<DirectParticipationDescriptor>(32);q.staging_count=al<std::uint32_t>();q.elig=al<EligibilityRecord>(kMaxLiveEligibilityRecords);q.live_elig=al<std::uint32_t>();q.directory=al<std::uint64_t>(kEligibilityClaimDirectoryCapacity);q.generations=al<std::uint32_t>(kMaxLiveEligibilityRecords);q.proposals=al<RouteTransportProposal>(R);q.claims=al<EligibilityBatchClaim>(CAP);q.scan_a=al<std::uint32_t>(CAP);q.scan_b=al<std::uint32_t>(CAP);q.free_slots=al<std::uint32_t>(kMaxLiveEligibilityRecords>kMaxDelayedSparsePackets?kMaxLiveEligibilityRecords:kMaxDelayedSparsePackets);q.owners=al<std::uint32_t>(kRouteTransportOwnerScratchCapacity);q.node_owners=al<std::uint32_t>(CAP);q.cursor=al<std::uint32_t>();q.metrics=al<AdultCoreMetrics>();State* ds=al<State>();
DirectNode hn[N]{};DirectRoute hr[R]{};std::uint64_t hi[R]{};for(std::uint32_t i=0;i<N;++i){hn[i].activation_q16=substrate::direct_adult_core::kQ16One;hn[i].route_offset=i<R?i:R;hn[i].active_route_count=i<R?1:0;hn[i].route_capacity=i<R?1:0;}for(std::uint32_t i=0;i<R;++i){hr[i].source=i;hr[i].target=i+1;hr[i].flags=kRouteFlagActive;hr[i].delay=1;hr[i].conductance_q16=substrate::direct_adult_core::kQ16One;hr[i].eligibility_q16=kQ16Half;hr[i].eligibility_context=0x5511+i;hr[i].eligibility_expires=150;hi[i]=11+i;}ck(cudaMemcpy(q.nodes,hn,sizeof(hn),cudaMemcpyHostToDevice),"nodes");ck(cudaMemcpy(q.routes,hr,sizeof(hr),cudaMemcpyHostToDevice),"routes");ck(cudaMemcpy(q.inc,hi,sizeof(hi),cudaMemcpyHostToDevice),"inc");std::vector<std::uint32_t> chain(kMaxDelayedSparsePackets);for(std::uint32_t i=0;i<kMaxDelayedSparsePackets;++i)chain[i]=i;ck(cudaMemcpy(q.next_free,chain.data(),sizeof(std::uint32_t)*chain.size(),cudaMemcpyHostToDevice),"chain");EligibilityRecord root{};root.ticket_id=0xabc;root.source_node=0;root.target_node=0;root.route_index=substrate::direct_adult_core::kInvalidIndex;root.context_signature=0x1111;root.eligibility_q16=kQ16Half;root.expiry_tick=150;root.live=1;root.claim_incarnation=88;root.authority=DirectParticipationAuthority::independent_external;root.authority_incarnation=77;root.lineage_expiry_tick=150;root.ancestry_depth=1;std::uint32_t one=1;ck(cudaMemcpy(q.elig,&root,sizeof(root),cudaMemcpyHostToDevice),"root");ck(cudaMemcpy(q.generations,&one,sizeof(one),cudaMemcpyHostToDevice),"gen");ck(cudaMemcpy(q.live_elig,&one,sizeof(one),cudaMemcpyHostToDevice),"live");NodeCausalParticipation rp{};rp.ticket_id=0xabc;rp.expiry_tick=150;rp.current_drive=1;rp.authority=DirectParticipationAuthority::independent_external;rp.authority_incarnation=77;rp.claim_incarnation=88;set_participation_eligibility_tail(&rp,(1ull<<32)|1ull);ck(cudaMemcpy(q.active,&rp,sizeof(rp),cudaMemcpyHostToDevice),"rootpart");init_state<<<1,1>>>(ds);ck(cudaDeviceSynchronize(),"init");
for(std::uint32_t step=0;step<5;++step){std::uint32_t tick=100+step;prepare_frontier<<<1,128>>>(q,tick);ck(cudaDeviceSynchronize(),"prepare");propose_step<<<1,1>>>(q,ds,tick);ck(cudaDeviceSynchronize(),"propose");materialize<<<1,128>>>(q,tick);ck(cudaDeviceSynchronize(),"materialize");deliver_due<<<1,128>>>(q,tick+1);ck(cudaDeviceSynchronize(),"deliver");observe_and_confirm<<<1,1>>>(q,ds,tick+1);ck(cudaDeviceSynchronize(),"observe");commit_frontier<<<1,128>>>(q);ck(cudaDeviceSynchronize(),"commit");}
State h{};ck(cudaMemcpy(&h,ds,sizeof(h),cudaMemcpyDeviceToHost),"state");bool green=!h.failed&&h.steps==5&&h.exec.completed&&h.lineage;std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_FIVE_DELIVERY_%s baseline_public_steps=0 direct_delivered_steps=%u bytes=79 depth=2 completed=%u rolling_lineage=%u final_parent_ref=%llu\n",green?"GREEN":"RED",h.steps,h.exec.completed,h.lineage,(unsigned long long)h.parent_ref);return green?0:1;}
