#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <cstdint>
#include <cstdio>
#include <vector>
#include "hardware_native/direct_causal_program_route_proposal.cuh"
#include "hardware_native/direct_language_plan_causal_lowering.cuh"
#include "hardware_native/direct_adult_core_kernels.cuh"
namespace cg=cooperative_groups;
using namespace substrate::direct_causal_program; using namespace substrate::direct_adult_core; using namespace substrate::direct_network;
constexpr std::uint32_t N=2,R=2,CAP=kMaxDelayedSparsePackets*kRouteTransportProducerWidth;
struct F{DirectNode*nodes;DirectRoute*routes;std::uint64_t*inc;std::int32_t*incoming;DelayedSparsePacket*packets;std::uint32_t*packet_live,*free_head,*next_free;DelayedPacketIdentity*identities;NodeCausalParticipation*active,*next;std::uint32_t*active_inc,*next_inc;DirectParticipationDescriptor*staging;std::uint32_t*staging_count;EligibilityRecord*elig;std::uint32_t*live_elig;std::uint64_t*directory;std::uint32_t*generations;RouteTransportProposal*proposals;EligibilityBatchClaim*claims;std::uint32_t*scan_a,*scan_b,*free_slots,*owners,*node_owners,*cursor;AdultCoreMetrics*metrics;DirectBoundaryPort*ports;MotorEvent*egress;std::uint32_t*ehead,*etail;AsynchronousTicket*tickets;std::uint32_t*ticket_count,*ticket_locks;DirectActionOccurrence*actions;DirectActionParticipationLink*links;ResidentPublicMotorTrajectory*trajectory;};
struct S{ProgramExecutionState exec;std::uint64_t parent_ref;std::uint32_t parent_slot,steps,lineage,failed,motor_events;};
__device__ Program program(){DirectLanguageMotorPlan lp{};lp.admitted=1;lp.step_count=5;lp.supporting_transitions=4;lp.distinct_channels=1;lp.revision_identity=0xCA11;for(std::uint32_t i=0;i<5;++i){lp.steps[i].node=1;lp.steps[i].channel=20;lp.steps[i].word=0x610000u+i;lp.steps[i].due_offset=i+1;}return lower_language_plan_to_causal_program(lp,0xabc,(1ull<<32)|1ull,150);}
__global__ void init_s(S*s){if(blockIdx.x||threadIdx.x)return;s->parent_ref=(1ull<<32)|1ull;s->parent_slot=0;s->lineage=1;auto p=program();if(!begin_execution(&s->exec,p,0xabc,100))s->failed=1;}
__global__ void prepare(F f,std::uint32_t tick){auto i=blockIdx.x*blockDim.x+threadIdx.x;auto slots=N*kMaxProvenanceSlotsPerNode;if(i<slots){auto v=read_participation_slot(f.active+i);if(v.ticket_id==0||v.expiry_tick<tick)v={};v.current_drive=0;publish_participation_slot(f.next+i,v);}if(i<N)f.next_inc[i]=0;}
__global__ void propose(F f,S*s,std::uint32_t tick){if(blockIdx.x||threadIdx.x||s->failed)return;auto pr=propose_program_step_via_direct_route(s->exec,f.elig[s->parent_slot],s->parent_ref,f.proposals,f.active,f.elig,f.generations,f.next_inc+1,f.nodes,N,f.routes,f.inc,R,tick,true);if(!pr.admitted)s->failed=1;}
__global__ void materialize(F f,std::uint32_t tick){auto g=cg::this_thread_block();materialize_route_transport_proposals(g,f.proposals,R,tick,N,f.cursor,f.packets,f.packet_live,f.free_head,f.next_free,f.identities,f.scan_a,f.scan_b,kMaxDelayedSparsePackets,f.free_slots,f.owners,f.next_inc,f.metrics);}
__global__ void deliver_due(F f,std::uint32_t tick){auto g=cg::this_thread_block();auto tid=g.thread_rank(),stride=g.size();auto live=*f.packet_live;for(std::uint32_t i=tid;i<CAP;i+=stride)f.claims[i]={};g.sync();for(std::uint32_t rank=tid;rank<live;rank+=stride){auto pi=f.next_free[rank];if(pi<kMaxDelayedSparsePackets&&f.packets[pi].live==static_cast<std::uint32_t>(DelayedPacketSlotState::published)&&f.packets[pi].due_tick<=tick)prepare_delayed_sparse_packet_batch(f.packets,f.identities,f.nodes,f.routes,f.inc,nullptr,N,R,f.incoming,f.elig,f.generations,f.claims,CAP,f.next_inc,pi,rank,tick,substrate::direct_adult_core::kQ16One,64,f.metrics);}g.sync();deterministic_eligibility_batch(g,f.claims,live*kRouteTransportProducerWidth,f.elig,f.live_elig,f.directory,f.generations,f.owners,f.scan_a,f.scan_b,f.free_slots,f.next,f.next_inc,f.node_owners,N,f.staging,f.staging_count,32,tick,f.metrics);}
__global__ void find_child(F f,S*s){if(blockIdx.x||threadIdx.x||s->failed)return;std::uint64_t child=0;std::uint32_t slot=substrate::direct_adult_core::kInvalidIndex;for(std::uint32_t i=0;i<kMaxLiveEligibilityRecords;++i){auto r=f.elig[i];if(r.live&&r.parent_eligibility_ref==s->parent_ref&&r.target_node==1&&r.ticket_id==0xabc){child=eligibility_record_ref(i,f.generations[i]);slot=i;s->lineage&=r.ancestry_depth==s->steps+2&&r.authority==DirectParticipationAuthority::independent_external&&r.route_index==(s->steps==0?0u:1u);break;}}if(!child||slot==substrate::direct_adult_core::kInvalidIndex){s->failed=1;return;}bool part=false;for(std::uint32_t j=0;j<kMaxProvenanceSlotsPerNode;++j){auto p=read_participation_slot(f.next+1*kMaxProvenanceSlotsPerNode+j);if(p.ticket_id==0xabc&&p.current_drive&&participation_eligibility_tail(p)==child){part=true;break;}}if(!part){s->failed=1;return;}s->parent_ref=child;s->parent_slot=slot;}
__global__ void confirm_motor(F f,S*s,std::uint32_t tick,std::uint32_t prior_tail){if(blockIdx.x||threadIdx.x||s->failed)return;auto tail=*f.etail;if(tail!=prior_tail+1){s->failed=1;return;}auto ev=f.egress[prior_tail%kMaxEgressQueueSize];auto c=due_candidate(s->exec,tick,0xabc);if(!c.admitted||ev.node!=c.step.node||ev.channel!=c.step.channel||ev.timestamp!=tick||ev.reserved!=0||!confirm_emitted_step(&s->exec,c,tick,ev.node,ev.channel)){s->failed=1;return;}++s->steps;++s->motor_events;}
__global__ void commit(F f){auto i=blockIdx.x*blockDim.x+threadIdx.x;auto slots=N*kMaxProvenanceSlotsPerNode;if(i<slots){publish_participation_slot(f.active+i,read_participation_slot(f.next+i));publish_participation_slot(f.next+i,{});}if(i<N){f.active_inc[i]=f.next_inc[i];f.next_inc[i]=0;}}
static void ck(cudaError_t x,const char*w){if(x!=cudaSuccess){std::fprintf(stderr,"%s: %s\n",w,cudaGetErrorString(x));std::exit(2);}} template<class T>T*al(std::size_t n=1){T*p=nullptr;ck(cudaMalloc(&p,sizeof(T)*n),"alloc");ck(cudaMemset(p,0,sizeof(T)*n),"zero");return p;}
int main(){F f{};f.nodes=al<DirectNode>(N);f.routes=al<DirectRoute>(R);f.inc=al<std::uint64_t>(R);f.incoming=al<std::int32_t>(N);f.packets=al<DelayedSparsePacket>(kMaxDelayedSparsePackets);f.packet_live=al<std::uint32_t>();f.free_head=al<std::uint32_t>();f.next_free=al<std::uint32_t>(kMaxDelayedSparsePackets);f.identities=al<DelayedPacketIdentity>(kDelayedPacketIdentityCapacity);f.active=al<NodeCausalParticipation>(N*kMaxProvenanceSlotsPerNode);f.next=al<NodeCausalParticipation>(N*kMaxProvenanceSlotsPerNode);f.active_inc=al<std::uint32_t>(N);f.next_inc=al<std::uint32_t>(N);f.staging=al<DirectParticipationDescriptor>(32);f.staging_count=al<std::uint32_t>();f.elig=al<EligibilityRecord>(kMaxLiveEligibilityRecords);f.live_elig=al<std::uint32_t>();f.directory=al<std::uint64_t>(kEligibilityClaimDirectoryCapacity);f.generations=al<std::uint32_t>(kMaxLiveEligibilityRecords);f.proposals=al<RouteTransportProposal>(R);f.claims=al<EligibilityBatchClaim>(CAP);f.scan_a=al<std::uint32_t>(CAP);f.scan_b=al<std::uint32_t>(CAP);f.free_slots=al<std::uint32_t>(kMaxLiveEligibilityRecords);f.owners=al<std::uint32_t>(kRouteTransportOwnerScratchCapacity);f.node_owners=al<std::uint32_t>(CAP);f.cursor=al<std::uint32_t>();f.metrics=al<AdultCoreMetrics>();f.ports=al<DirectBoundaryPort>();f.egress=al<MotorEvent>(kMaxEgressQueueSize);f.ehead=al<std::uint32_t>();f.etail=al<std::uint32_t>();f.tickets=al<AsynchronousTicket>(kMaxAsynchronousTickets);f.ticket_count=al<std::uint32_t>();f.ticket_locks=al<std::uint32_t>(kMaxAsynchronousTickets);f.actions=al<DirectActionOccurrence>(kMaxAsynchronousTickets);f.links=al<DirectActionParticipationLink>(kMaxAsynchronousTickets*kMaxActionParticipationLinks);f.trajectory=al<ResidentPublicMotorTrajectory>();S*ds=al<S>();
DirectNode n[N]{};for(auto&i:n)i.activation_q16=substrate::direct_adult_core::kQ16One;n[0].route_offset=0;n[0].active_route_count=1;n[0].route_capacity=1;n[1].route_offset=1;n[1].active_route_count=1;n[1].route_capacity=1;DirectRoute r[R]{};r[0].source=0;r[0].target=1;r[1].source=1;r[1].target=1;for(std::uint32_t i=0;i<R;++i){r[i].flags=kRouteFlagActive;r[i].delay=1;r[i].conductance_q16=substrate::direct_adult_core::kQ16One;r[i].eligibility_q16=kQ16Half;r[i].eligibility_context=0x5511+i;r[i].eligibility_expires=150;}std::uint64_t inc[R]={11,12};DirectBoundaryPort port{};port.node=1;port.channel=20;port.role_mask=static_cast<std::uint32_t>(BoundaryRole::motor);port.physical_route=1;port.parent_route=0;ck(cudaMemcpy(f.nodes,n,sizeof(n),cudaMemcpyHostToDevice),"nodes");ck(cudaMemcpy(f.routes,r,sizeof(r),cudaMemcpyHostToDevice),"routes");ck(cudaMemcpy(f.inc,inc,sizeof(inc),cudaMemcpyHostToDevice),"inc");ck(cudaMemcpy(f.ports,&port,sizeof(port),cudaMemcpyHostToDevice),"port");std::vector<std::uint32_t> chain(kMaxDelayedSparsePackets);for(std::uint32_t i=0;i<kMaxDelayedSparsePackets;++i)chain[i]=i;ck(cudaMemcpy(f.next_free,chain.data(),sizeof(std::uint32_t)*chain.size(),cudaMemcpyHostToDevice),"chain");EligibilityRecord root{};root.ticket_id=0xabc;root.source_node=0;root.target_node=0;root.route_index=substrate::direct_adult_core::kInvalidIndex;root.eligibility_q16=kQ16Half;root.expiry_tick=150;root.live=1;root.claim_incarnation=88;root.authority=DirectParticipationAuthority::independent_external;root.authority_incarnation=77;root.lineage_expiry_tick=150;root.ancestry_depth=1;std::uint32_t one=1;ck(cudaMemcpy(f.elig,&root,sizeof(root),cudaMemcpyHostToDevice),"root");ck(cudaMemcpy(f.generations,&one,sizeof(one),cudaMemcpyHostToDevice),"gen");ck(cudaMemcpy(f.live_elig,&one,sizeof(one),cudaMemcpyHostToDevice),"live");NodeCausalParticipation rp{};rp.ticket_id=0xabc;rp.expiry_tick=150;rp.current_drive=1;rp.authority=DirectParticipationAuthority::independent_external;rp.authority_incarnation=77;rp.claim_incarnation=88;set_participation_eligibility_tail(&rp,(1ull<<32)|1ull);ck(cudaMemcpy(f.active,&rp,sizeof(rp),cudaMemcpyHostToDevice),"rootpart");init_s<<<1,1>>>(ds);ck(cudaDeviceSynchronize(),"init");DirectBrain brain{};brain.nodes=f.nodes;brain.node_count=N;brain.routes=f.routes;brain.route_capacity=R;brain.route_incarnations=f.inc;brain.boundary_ports=f.ports;brain.boundary_port_count=1;
for(std::uint32_t k=0;k<5;++k){auto t=100+k;prepare<<<1,128>>>(f,t);ck(cudaDeviceSynchronize(),"prepare");propose<<<1,1>>>(f,ds,t);ck(cudaDeviceSynchronize(),"propose");materialize<<<1,128>>>(f,t);ck(cudaDeviceSynchronize(),"mat");deliver_due<<<1,128>>>(f,t+1);ck(cudaDeviceSynchronize(),"deliver");find_child<<<1,1>>>(f,ds);ck(cudaDeviceSynchronize(),"child");std::uint32_t before=0;ck(cudaMemcpy(&before,f.etail,sizeof(before),cudaMemcpyDeviceToHost),"tailbefore");emit_motor_events_kernel<<<1,1>>>(brain,f.nodes,f.routes,f.inc,R,f.ports,nullptr,nullptr,nullptr,0,1,f.egress,f.ehead,f.etail,f.tickets,f.ticket_count,f.ticket_locks,f.actions,f.links,kMaxActionParticipationLinks,f.trajectory,1,nullptr,nullptr,64,f.staging,f.staging_count,32,f.next,N,f.next_inc,f.elig,f.generations,nullptr,f.metrics,t+1,nullptr,nullptr,nullptr,f.incoming,0);ck(cudaDeviceSynchronize(),"motor");confirm_motor<<<1,1>>>(f,ds,t+1,before);ck(cudaDeviceSynchronize(),"confirm");commit<<<1,128>>>(f);ck(cudaDeviceSynchronize(),"commit");}
S h{};ck(cudaMemcpy(&h,ds,sizeof(h),cudaMemcpyDeviceToHost),"state");bool green=!h.failed&&h.steps==5&&h.motor_events==5&&h.exec.completed&&h.lineage;std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_FIVE_MOTOR_%s motor_events=%u completed=%u rolling_lineage=%u final_parent_ref=%llu frozen_surface=0\n",green?"GREEN":"RED",h.motor_events,h.exec.completed,h.lineage,(unsigned long long)h.parent_ref);return green?0:1;}
