#include <cuda_runtime.h>
#include <cooperative_groups.h>
#include <cstdint>
#include <cstdio>
#include <vector>
#include "hardware_native/direct_causal_program_route_proposal.cuh"
namespace cg=cooperative_groups;
using namespace substrate::direct_causal_program;
using namespace substrate::direct_adult_core;
using namespace substrate::direct_network;
struct Pointers{DirectNode* nodes;DirectRoute* routes;std::uint64_t* inc;std::uint64_t* opportunity;std::int32_t* incoming;DelayedSparsePacket* packets;std::uint32_t* packet_live;std::uint32_t* free_head;std::uint32_t* next_free;DelayedPacketIdentity* identities;NodeCausalParticipation* active;NodeCausalParticipation* next;std::uint32_t* active_incomplete;std::uint32_t* next_incomplete;DirectParticipationDescriptor* staging;std::uint32_t* staging_count;EligibilityRecord* elig;std::uint32_t* live_elig;std::uint64_t* directory;std::uint32_t* generations;RouteTransportProposal* proposals;EligibilityBatchClaim* claims;std::uint32_t* scan_a;std::uint32_t* scan_b;std::uint32_t* free_slots;std::uint32_t* owners;std::uint32_t* node_owners;std::uint32_t* cursor;AdultCoreMetrics* metrics;};
struct Receipt{std::uint32_t proposed,materialized,child_found,participation_found,child_depth,child_target;std::uint64_t child_ref,parent_ref;};
__device__ Program make_program(){Program p{};p.identity=0xCA11;p.initiation_participation_identity=0xabc;p.initiation_parent_eligibility_ref=(1ull<<32)|1ull;p.initiation_expiry_tick=140;p.depth=2;p.step_count=5;for(std::uint32_t i=0;i<5;++i){p.steps[i].node=i+1;p.steps[i].channel=20+i;p.steps[i].due_offset=i+1;}return p;}
__global__ void propose_kernel(Pointers q,Receipt* out){if(blockIdx.x||threadIdx.x)return;Program p=make_program();ProgramExecutionState e{};begin_execution(&e,p,0xabc,100);auto pr=propose_program_step_via_direct_route(e,q.elig[0],p.initiation_parent_eligibility_ref,q.proposals,q.active,q.elig,q.generations,q.next_incomplete+1,q.nodes,2,q.routes,q.inc,1,100,true);out->proposed=pr.admitted;out->parent_ref=p.initiation_parent_eligibility_ref;}
__global__ void materialize_kernel(Pointers q){auto g=cg::this_thread_block();materialize_route_transport_proposals(g,q.proposals,1u,100u,2u,q.cursor,q.packets,q.packet_live,q.free_head,q.next_free,q.identities,q.scan_a,q.scan_b,kMaxDelayedSparsePackets,q.free_slots,q.owners,q.next_incomplete,q.metrics);}
__global__ void deliver_kernel(Pointers q){auto g=cg::this_thread_block();RouteTransportPhaseView v{q.proposals,q.claims,kMaxDelayedSparsePackets*kRouteTransportProducerWidth,q.scan_a,q.scan_b,kMaxDelayedSparsePackets*kRouteTransportProducerWidth,q.free_slots,q.owners,q.node_owners,q.cursor};execute_deterministic_route_transport(g,q.nodes,q.routes,q.inc,q.opportunity,2u,1u,q.incoming,q.packets,q.packet_live,q.free_head,q.next_free,q.identities,q.active,q.next,q.active_incomplete,q.next_incomplete,q.staging,q.staging_count,16u,q.elig,q.live_elig,q.directory,q.generations,v,101u,substrate::direct_adult_core::kQ16One,64u,1u,q.metrics);}
__global__ void inspect_kernel(Pointers q,Receipt* out){if(blockIdx.x||threadIdx.x)return;out->materialized=*q.live_elig>=2u;for(std::uint32_t i=0;i<kMaxLiveEligibilityRecords;++i){auto r=q.elig[i];if(r.live&&r.parent_eligibility_ref==out->parent_ref&&r.target_node==1u&&r.ticket_id==0xabc){out->child_found=1;out->child_depth=r.ancestry_depth;out->child_target=r.target_node;out->child_ref=eligibility_record_ref(i,q.generations[i]);break;}}for(std::uint32_t s=0;s<kMaxProvenanceSlotsPerNode;++s){auto p=read_participation_slot(q.next+1u*kMaxProvenanceSlotsPerNode+s);if(p.ticket_id==0xabc&&participation_eligibility_tail(p)==out->child_ref&&p.current_drive){out->participation_found=1;break;}}}
static void ck(cudaError_t s,const char* w){if(s!=cudaSuccess){std::fprintf(stderr,"%s: %s\n",w,cudaGetErrorString(s));std::exit(2);}}
template<class T> static T* alloc(std::size_t n=1){T* p=nullptr;ck(cudaMalloc(&p,sizeof(T)*n),"alloc");ck(cudaMemset(p,0,sizeof(T)*n),"zero");return p;}
int main(){Pointers q{};q.nodes=alloc<DirectNode>(2);q.routes=alloc<DirectRoute>();q.inc=alloc<std::uint64_t>();q.opportunity=alloc<std::uint64_t>();q.incoming=alloc<std::int32_t>(2);q.packets=alloc<DelayedSparsePacket>(kMaxDelayedSparsePackets);q.packet_live=alloc<std::uint32_t>();q.free_head=alloc<std::uint32_t>();q.next_free=alloc<std::uint32_t>(kMaxDelayedSparsePackets);q.identities=alloc<DelayedPacketIdentity>(kDelayedPacketIdentityCapacity);q.active=alloc<NodeCausalParticipation>(2*kMaxProvenanceSlotsPerNode);q.next=alloc<NodeCausalParticipation>(2*kMaxProvenanceSlotsPerNode);q.active_incomplete=alloc<std::uint32_t>(2);q.next_incomplete=alloc<std::uint32_t>(2);q.staging=alloc<DirectParticipationDescriptor>(16);q.staging_count=alloc<std::uint32_t>();q.elig=alloc<EligibilityRecord>(kMaxLiveEligibilityRecords);q.live_elig=alloc<std::uint32_t>();q.directory=alloc<std::uint64_t>(kEligibilityClaimDirectoryCapacity);q.generations=alloc<std::uint32_t>(kMaxLiveEligibilityRecords);q.proposals=alloc<RouteTransportProposal>();constexpr std::uint32_t CAP=kMaxDelayedSparsePackets*kRouteTransportProducerWidth;q.claims=alloc<EligibilityBatchClaim>(CAP);q.scan_a=alloc<std::uint32_t>(CAP);q.scan_b=alloc<std::uint32_t>(CAP);q.free_slots=alloc<std::uint32_t>(kMaxLiveEligibilityRecords>kMaxDelayedSparsePackets?kMaxLiveEligibilityRecords:kMaxDelayedSparsePackets);q.owners=alloc<std::uint32_t>(kRouteTransportOwnerScratchCapacity);q.node_owners=alloc<std::uint32_t>(CAP);q.cursor=alloc<std::uint32_t>();q.metrics=alloc<AdultCoreMetrics>();
DirectNode hn[2]{};hn[0].activation_q16=substrate::direct_adult_core::kQ16One;hn[0].route_offset=0;hn[0].active_route_count=1;hn[0].route_capacity=1;hn[1].activation_q16=kQ16Half;DirectRoute hr{};hr.source=0;hr.target=1;hr.flags=kRouteFlagActive;hr.delay=1;hr.conductance_q16=substrate::direct_adult_core::kQ16One;hr.eligibility_q16=kQ16Half;hr.eligibility_context=0x5511;hr.eligibility_expires=140;std::uint64_t hi=11;ck(cudaMemcpy(q.nodes,hn,sizeof(hn),cudaMemcpyHostToDevice),"nodes");ck(cudaMemcpy(q.routes,&hr,sizeof(hr),cudaMemcpyHostToDevice),"route");ck(cudaMemcpy(q.inc,&hi,sizeof(hi),cudaMemcpyHostToDevice),"inc");std::vector<std::uint32_t> chain(kMaxDelayedSparsePackets);for(std::uint32_t i=0;i<kMaxDelayedSparsePackets;++i)chain[i]=i;ck(cudaMemcpy(q.next_free,chain.data(),sizeof(std::uint32_t)*chain.size(),cudaMemcpyHostToDevice),"chain");
EligibilityRecord root{};root.ticket_id=0xabc;root.source_node=0;root.target_node=0;root.route_index=substrate::direct_adult_core::kInvalidIndex;root.context_signature=0x1111;root.eligibility_q16=kQ16Half;root.expiry_tick=140;root.live=1;root.claim_incarnation=88;root.route_incarnation=0;root.authority=DirectParticipationAuthority::independent_external;root.authority_incarnation=77;root.parent_eligibility_ref=0;root.lineage_expiry_tick=140;root.ancestry_depth=1;std::uint32_t one=1;ck(cudaMemcpy(q.elig,&root,sizeof(root),cudaMemcpyHostToDevice),"root");ck(cudaMemcpy(q.generations,&one,sizeof(one),cudaMemcpyHostToDevice),"gen");ck(cudaMemcpy(q.live_elig,&one,sizeof(one),cudaMemcpyHostToDevice),"live");NodeCausalParticipation part{};part.ticket_id=0xabc;part.expiry_tick=140;part.current_drive=1;part.authority=DirectParticipationAuthority::independent_external;part.authority_incarnation=77;part.claim_incarnation=88;set_participation_eligibility_tail(&part,(1ull<<32)|1ull);ck(cudaMemcpy(q.active,&part,sizeof(part),cudaMemcpyHostToDevice),"part");Receipt* d=alloc<Receipt>();propose_kernel<<<1,1>>>(q,d);ck(cudaDeviceSynchronize(),"propose");materialize_kernel<<<1,128>>>(q);ck(cudaDeviceSynchronize(),"materialize");deliver_kernel<<<1,128>>>(q);ck(cudaDeviceSynchronize(),"deliver");inspect_kernel<<<1,1>>>(q,d);ck(cudaDeviceSynchronize(),"inspect");Receipt h{};ck(cudaMemcpy(&h,d,sizeof(h),cudaMemcpyDeviceToHost),"receipt");bool green=h.proposed&&h.materialized&&h.child_found&&h.participation_found&&h.child_depth==2&&h.child_target==1&&h.child_ref!=0;std::printf("FOUNDRY_DIRECT_CAUSAL_PROGRAM_DELIVERY_%s baseline_public_steps=0 direct_delivered_steps=%u bytes=79 depth=2 child_depth=%u child_participation=%u child_ref=%llu\n",green?"GREEN":"RED",green?1u:0u,h.child_depth,h.participation_found,(unsigned long long)h.child_ref);return green?0:1;}
